/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todolist;


public class App {

    public static void main(String[] args) {
        InputReader reader = new InputReader();
        reader.start();
    }
}
